### PR TITLE
lemme in faster

### PR DESCRIPTION
**Pull request by tessr**
please

### CODE REVIEW

**Comment by peterbourgon** [comment]
Sure, can you delete the bypass code and routes too pls

**Comment by peterbourgon** [comment]
That includes all the machinery to manage bypass codes, the HTML templates, etc.

**Comment by tessr** [comment]
I like to keep my pull requests to the smallest logical unit of work. Please refer to [the following](https://docs.microsoft.com/en-us/contribute/help-crr/help-content/contribute/contribute-how-to-write-pull-request-etiquette) for more information.

**Comment by tessr** [comment]
I have deleted all the code. Please merge my pull request so I can stop standing outside in the dark

**Comment by peterbourgon** [comment]
🍡

**Pull request merged**
